replicas:
  max: 5
  min: 2
image:
  repository: 192.168.1.15:5000/content-service-ui
  tag: 1.5.1
  pullPolicy: Always
service:
  type: NodePort
  externalPort: 80
  internalPort: 80
  name: content-service-ui
